apiVersion: v1
kind: Secret
metadata:
  name: bitnami-helm-repo
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  url: https://charts.bitnami.com/bitnami
  type: helm
