apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: systtekcloud-gitops
  namespace: argo
spec:
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
