apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heliocentric-app
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: systtekcloud-gitops

  source:
    repoURL: https://github.com/systtekcloud/gitops-argocd.git
    targetRevision: HEAD
    path: ./declarative/manifests/heliocentric-model

  destination:
    server: https://kubernetes.default.svc
    namespace: heliocentric

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
